language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t xavbm/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true xavbm/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: Docker-react
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ca-central-1-457912634729"
  bucket_path: "Docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY